from enum import Enum


class UserStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INVITED = "INVITED"
    DISABLED = "DISABLED"


class MeetingStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    ACTIVE = "ACTIVE"
    ENDED = "ENDED"
    CANCELED = "CANCELED"


class ParticipantRole(str, Enum):
    HOST = "HOST"
    CO_HOST = "CO_HOST"
    PARTICIPANT = "PARTICIPANT"


class ParticipantStatus(str, Enum):
    INVITED = "INVITED"
    JOINED = "JOINED"
    LEFT = "LEFT"
    REMOVED = "REMOVED"


class InvitationStatus(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    DECLINED = "DECLINED"
    EXPIRED = "EXPIRED"
    CANCELED = "CANCELED"


class MeetingEventType(str, Enum):
    MEETING_CREATED = "MEETING_CREATED"
    MEETING_STARTED = "MEETING_STARTED"
    MEETING_ENDED = "MEETING_ENDED"
    PARTICIPANT_JOINED = "PARTICIPANT_JOINED"
    PARTICIPANT_LEFT = "PARTICIPANT_LEFT"
    PARTICIPANT_REMOVED = "PARTICIPANT_REMOVED"
    PARTICIPANT_MUTED = "PARTICIPANT_MUTED"
    PARTICIPANT_UNMUTED = "PARTICIPANT_UNMUTED"
    ALL_PARTICIPANTS_MUTED = "ALL_PARTICIPANTS_MUTED"
    HOST_CHANGED = "HOST_CHANGED"
    CO_HOST_ASSIGNED = "CO_HOST_ASSIGNED"